{% set name = "aliyun-python-sdk-core" %}
{% set version = "2.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54f66a53e193c61c5e16ea4505a0cab43543f8ad2ef22833f69c4d5e5151c17d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jmespath >=0.9.3,<1.0.0
    - cryptography >=2.9.2

test:
  imports:
    - aliyunsdkcore

about:
  home: https://github.com/aliyun/aliyun-openapi-python-sdk
  license: Apache-2.0
  license_file: LICENSE
  summary: The core module of Aliyun Python SDK.

  description: |
    The Alibaba Cloud Python Software Development Kit (SDK) allows you to
    access Alibaba Cloud services such as Elastic Compute Service (ECS),
    Object Storage Service (OSS), and Resource Access Management (RAM).
    You can access Alibaba Cloud services without the need to handle API
    related tasks, such as signing and constructing your requests.

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - maxhora
